### PR TITLE
support kotlin

### PR DESCRIPTION
**Pull request by shuntakeuch1**
I wrote the code corresponding to kotlin
Please import if you like.

### CODE REVIEW

**Comment by syohex** [comment]
I don't know Kotlin well. However this PR does not work against the file which name starts with small case character like `a.kt`. Because `kotlinc` compiles `a.kt` and generate `AKt.class`. `quickrun.el` does not support such case, however I suppose you can avoid this issue by below hack. 

```diff
diff --git a/quickrun.el b/quickrun.el
index d6dc348..2f5bc11 100644
--- a/quickrun.el
+++ b/quickrun.el
@@ -438,7 +438,10 @@
                   (:outputter . quickrun--gnuplot-outputter)))
     ("kotlin" . ((:command . "kotlin")
                  (:compile-only . "kotlinc -Werror %o %s")
-                 (:exec    . ("kotlinc %o %s" "%c %NKt %a"))
+                 (:exec    . ("kotlinc %o %s"
+                              (lambda ()
+                                (let ((file (file-name-nondirectory (file-name-sans-extension (buffer-file-name)))))
+                                  (format "%%c %sKt %%a" (upcase-initials file))))))
                  (:remove  . ("%nKt.class"))
                  (:tempfile . nil)
                  (:description . "Compile Kotlin file and execute"))))
```

BTW I suppose it is no problem if no one uses file name like `a.kt`, `hello.kt`

**Comment by shuntakeuch1** [comment]
@syohex 
Code review thanks.
The advice was very good, so I just used it.

**Comment by syohex** [comment]
Looks good

**Comment by jcs090218** [comment]
Thanks!

**Pull request merged**
