### PR TITLE
 Check major mode in buffers not visiting a file

### PR DESCRIPTION
**Pull request by calancha**
* quickrun.el (quickrun--command-key): Check major mode in buffers not visiting a file

;; Suppose you create a new buffer (not visiting a file) in sh-mode:
C-x b foo RET
M-x sh-mode RET
;; Now you write or paste some code:
echo "foobar"
;; It's nice if the language is automatically detected (i.e. without being prompted):
M-x quickrun RET

### CODE REVIEW

**Comment by calancha** [comment]
Automatically detect language for a buffer not visiting a file.

**Comment by jcs090218** [comment]
This make sense to me. Does the code still work? Sorry this has been a while! 😅

**Comment by calancha** [comment]
I have rebased my branch with the master branch; the recipe above still works.

**Comment by jcs090218** [comment]
Merged! Thanks!

**Pull request merged**
